
name: Cut release tag

on:
   workflow_dispatch:
      inputs:
         message:
            description: 'Message'
            default: 'Release from branch'
            required: true

jobs:
   cut-release:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout branch
           uses: actions/checkout@v2
         - name: echo
           run: echo ${GITHUB_RUN_NUMBER}
         - name: Tag
           run: git tag $(date "+release_%Y%m%d")_"${GITHUB_RUN_NUMBER}"
         - name: Push
           run: git push --tags
